### PR TITLE
Delete entities

### PR DESCRIPTION
**Pull request by simleo**
First draft. See #62.

### CODE REVIEW

**Review by cedricdcc — CHANGES_REQUESTED** [review]
This seems like a better implementation of what I had.
One request is it ok to implement the following function.
`def delete_file(self, entity_id):
        	return self.delete(self.dereference(entity_id= entity_id))`

**Comment by simleo** [comment]
> One request is it ok to implement the following function.
> `def delete_file(self, entity_id): return self.delete(self.dereference(entity_id= entity_id))`

That would be `add_file`'s counterpart. However, one difference with adding is that when deleting you are supposed to already have the file as a `File` entity, so there should be no need of specialized functions that do what you are suggesting (deleting by id, in this case). One possible use case would be to make things easier for the CLI tool. I haven't looked into that yet, could be that it's easy enough to dereference on the fly in the CLI implementation.

Can you see another use case for `delete_file` that I'm missing?

**Comment by cedricdcc** [comment]
The Usecase was that the user gives the id of the file to be deleted. This didn't work directly hence the `self.dereference(entity_id= entity_id)` in the `delete_file(self, entity_id)` function. I will test on my end if this would be a problem without the dereference of the entity_id.

**Comment by fbacall** [comment]
How about putting the delete method on the entity itself?

`crate.dereference('bla').delete()`

**Comment by marc-portier** [comment]
> `crate.dereference('bla').delete()`

like it!

@cedricdcc I'm pretty sure you will need the dereference 

@simleo straightforward use case would be via the cli --> I pass an entity_id and the ro-crate-folder (or zip) path of an existing crate via the cli -- hoping to achieve that the mentioned entity_id gets removed from the crate ?  
(and similarly when you consider a webbased sessionless UI that allows to view, select(by id?), remove content from a crate)

**Comment by cedricdcc** [comment]
Yeah but in code it looks like this` crate.delete(crate.dereference(entity_todelete))` since the crate.dereference return a file object for which there is an Attributionerror

**Comment by simleo** [comment]
Deletion by id added in 93696a7. There's no need to add specific functions for specific entities, I just leveraged Python's dynamic typing. If you pass something that's not an `Entity` to `delete`, the method will try dereferencing it, so it should work on any entity. Note that, in the case of data entities referring to local files and dirs, the path must be the same as the crate's id (check out `test_delete_by_id`).

**Comment by simleo** [comment]
> How about putting the delete method on the entity itself?
> 
> `crate.dereference('bla').delete()`

Done in a46b5d3

**Review by cedricdcc — APPROVED** [review]

**Comment by stain** [comment]
Checks are happy, shall we merge this, @simleo ?

**Comment by simleo** [comment]
> Checks are happy, shall we merge this, @simleo ?

They're happy because they don't check enough :slightly_smiling_face:. See the comments in [`test_delete_refs`](https://github.com/ResearchObject/ro-crate-py/pull/65/files#diff-b7713b8731a4d1f895063e58f31f8ab54f7bb6ca0e2b1712d85683874d94a6e6R191) and the discussion in #62.

I think we can add this feature as it is (and perhaps get back to it later), but we should add some info to the docstring explaining that the method is not going to fix any inconsistencies for you.

**Pull request merged**
