### PR TITLE
No metadata entry for the HTML preview

### PR DESCRIPTION
**Pull request by simleo**
This PR contains a set of changes to make the library _not_ list the [HTML preview](https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-website-ro-crate-previewhtml-and-ro-crate-preview_files) among the metadata. The background is https://github.com/ResearchObject/ro-crate/issues/106, where the question of whether it should be listed or not is being discussed (with a preference for _not_ listing it, it seems?). Up to now, both this library and WorkflowHub chose to include the preview among the metadata as a `CreativeWork` with an `about` property pointing to the crate itself. This PR explores what the change looks like from an implementation's standpoint. The main highlights are the following:

* The library retains the ability to generate the HTML preview from the crate upon request
* The `gen_preview` flag is now an argument to the `write` method (it only matters when the crate is written out)
* The code got simplified since there's one less "special" entity to manage

One thing to notice is that if the library now reads a legacy crate that does list the preview (e.g., from WorkflowHub) as a `CreativeWork`, the record changes from:

```javascript
{
    "@id": "ro-crate-preview.html",
    "@type": "CreativeWork",
    "about": {
        "@id": "./"
    }
}
```

to:

```javascript
{
    "@id": "#ro-crate-preview.html",
    "@type": "CreativeWork",
    "about": {
        "@id": "./"
    }
}
```

I.e., it's not considered a data entity anymore. This is a good opportunity to review (in a separate issue / PR) what the library does and does not consider a data entity and how it reaches that decision (linked to #89).

### CODE REVIEW

**Comment by stain** [comment]
I don't think it should change it to `#ro-crate-preview.html` (which would just resolve to this same JSON block) - the creative work is still at the relative URI `ro-crate-preview.html` in the form of HTML even if this is not listed as a data entity with `hasPart`

**Comment by simleo** [comment]
> I don't think it should change it to `#ro-crate-preview.html`

Yes. I think this "functionality" that blindly adds a leading `#` to all context entities whose ID is not a full URL should be considered a bug, though it's probably been added to aid the user. See also #92.

**Comment by simleo** [comment]
Re: this PR: discussed at the biohackathon with @stain and @fbacall.

Stian:
> when referencing other RO-Crates it is useful to include that link so browsers can jump from preview to preview. And RO-Crates are self-declaring. So it might seem unusual why the view of the RO-Crate itself is not described in JSON-LD.  However I don't think it should be under hasPart - I think it should be similar to the ro-crate-metadata.json entity, but with text/html as encodingFormat

Finn:
> in ro-crate-ruby, the preview is listed in the graph, but is not linked from hasPart

So I guess we're probably going to ditch this PR and update the preview entity to include `"encodingFormat": "text/html"` instead (we're already _not_ including it in `hasPart`). Leaving it open for now, we probably want to bring the matter up again at the next community meeting.

**Comment by simleo** [comment]
We talked about the preview tonight at the community meeting. What exactly to do with it is still a matter of discussion, but there seems to be agreement on the fact that we do want to list it in the metadata, so we can close this.

**Pull request closed without merging**
